### ISSUE TITLE
Allow to apply a custom theme

### ISSUE THREAD

**Issue by quijote** [mar10/wunderbaum#21]
Dark mode is omnipresent nowadays. I would like to render a Wunderbaum with different colors using a custom dark CSS theme. E.g. I would like to add something like the following to my application: 

```typescript
import 'wunderbaum/dist/wunderbaum.css'
import './wunderbaum-theme-dark.css'
```

And `wunderbaum-theme-dark.css` could then override some [CSS variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) like this:

```css
:root {
  --wb-error-color: #b5373b;
  --wb-node-text-color: #56534c;
  --wb-bg-highlight-color: #26a0da;
  --wb-header-color: #dedede;
  --wb-background-color: white;
  --wb-alternate-row-color: #f7f7f7;
  --wb-alternate-row-color-hover: #f3f3f3;
  --wb-focus-border-color: #275dc5;
}
```

I am not sure if it makes sense exactly like that (with `:root`), but I saw other libraries that easily allowed to customize styles like this. I tried to override colors from the current CSS but it seemed a bit cumbersome as the same color seems to be repeated in multiple CSS rules (via expanded variables from SCSS).
