### ISSUE TITLE
Treegrid does not render properly

### ISSUE THREAD

**Issue by quijote** [mar10/wunderbaum#22]
A Treegrid in my code did not render properly. I debugged for a while and in the end found out that [the demo](https://mar10.github.io/wunderbaum/demo/#demo-grid) relies on the following CSS rule from `style.css` to work properly:

```css
* {
    box-sizing: border-box;
}
```

My code did not have this and all horizontal offsets looked a bit weird. 

`wunderbaum.css` comes with:

```css
div.wunderbaum {
  box-sizing: border-box;
}
```

But I think this should be extended to something like the following to include all child elements:

```css
div.wunderbaum * {
  box-sizing: border-box;
}
```
