### ISSUE TITLE
wb-helper-end is not applied to column header

### ISSUE THREAD

**Issue by quijote** [mar10/wunderbaum#23]
I created a treegrid with numeric columns. Similar to [the demo](https://mar10.github.io/wunderbaum/demo/#demo-grid) I used `classes: "wb-helper-end"` to align everything to the right.

However the column header is still aligned to the left. Behavior can be observed in the demo grid as well.

![image](https://github.com/mar10/wunderbaum/assets/613158/ac5fb4d2-3034-476c-9dcd-2075bb83806c)

**Comment by mar10** [comment]
v0.3.4 now adds the classes to the header as well.

However I think this may not be the best solution, since user may want to have different classes in header- and data-cells for that column. For example have all headers centered, even for right-aligned numeric data.
A separate option could be a better approach:
```css
  columns: [
    { title: "test", id: "*", width: "200px" },
    {
      title: "Count",
      id: "count",
      headerClasses: "wb-helper-end",
      classes: "wb-helper-end",
    },

```
What do you think?
